genericPagingSortingClean/Controllers/dbItemTypeOneController.cs
using businessLogic.viewModelFactories;
using businessLogic.viewModels;
using dbPersistance;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace genericPagingSortingClean.Controllers
{
    public class dbItemTypeOneController : genericCrudListController<dbItemTypeOne, genericModelCollection, genericCollectionItem<dbItemTypeOne>, genericListModelFactory<dbItemTypeOne, genericModelCollection, genericCollectionItem<dbItemTypeOne>>>
    {

    }
}

genericPagingSortingClean/Controllers/dbItemTypeThreeController.cs
using businessLogic.viewModelFactories;
using businessLogic.viewModels;
using dbPersistance;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace genericPagingSortingClean.Controllers
{
    public class dbItemTypeThreeController : genericCrudListController<dbItemTypeThree, genericModelCollection, genericCollectionItem<dbItemTypeThree>, genericListModelFactory<dbItemTypeThree, genericModelCollection, genericCollectionItem<dbItemTypeThree>>>
    {

    }
}

genericPagingSortingClean/Controllers/dbItemTypeTwoController.cs
using businessLogic.viewModelFactories;
using businessLogic.viewModels;
using dbPersistance;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace genericPagingSortingClean.Controllers
{
    public class dbItemTypeTwoController 
        : genericCrudListController<dbItemTypeTwo, genericModelCollection, genericCollectionItem<dbItemTypeTwo>, genericListModelFactory<dbItemTypeTwo, genericModelCollection, genericCollectionItem<dbItemTypeTwo>>>
    {

    }
}

genericPagingSortingClean/Controllers/homeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace genericPagingSortingClean.Controllers
{
    public class homeController : Controller
    {
        // GET: home
        public ActionResult Index()
        {
            return View();
        }
    }
}

genericPagingSortingClean/Views/home/index.cshtml
@{
    ViewBag.Title = "index";
    Layout = "~/Views/shared/_Layout.cshtml";
}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Paging & Sorting</a>
    <div class="float-right">
        @Html.ActionLink("Pull Data Item #1", "pagedList", "dbItemTypeOne", null, new { @class = "btn btn-outline-success my-2 my-sm-0" })
        @Html.ActionLink("Pull Data Item #2", "pagedList", "dbItemTypeTwo", null, new { @class = "btn btn-outline-success my-2 my-sm-0" })
        @Html.ActionLink("Pull Data Item #3", "pagedList", "dbItemTypeThree", null, new { @class = "btn btn-outline-success my-2 my-sm-0" })
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">

        </div>
    </div>
</div>